# Generated by Django 5.2.17 on 2026-09-29 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-]+$', 'Only letters, numbers, underscores and hyphens are allowed.')])),
                ('timestamp', models.CharField(max_length=50)),
                ('duration_minutes', models.FloatField()),
                ('subject', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='focus_focus_user_id_c05da6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='focus_log_user_client_id_unique'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0), ('duration_minutes__lte', 1440)), name='focus_log_duration_range')],
            },
        ),
    ]
