# Generated by Django 5.2.17 on 2026-09-29 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-]+$', 'Only letters, numbers, underscores and hyphens are allowed.')])),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Personal', 'Personal'), ('Career', 'Career'), ('Health', 'Health'), ('Projects', 'Projects')], max_length=50)),
                ('target_date', models.CharField(blank=True, default='', max_length=50)),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_tip', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='goals_goal_user_id_7dd455_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='goals_goal_user_client_id_unique'), models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='goals_goal_progress_range')],
            },
        ),
    ]
