from django.conf import settings
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
    RegexValidator,
)
from django.db import models

client_id_validator = RegexValidator(
    r"^[a-zA-Z0-9_\-]+$",
    "Only letters, numbers, underscores and hyphens are allowed.",
)


class Goal(models.Model):
    """An academic / personal goal with nested milestones and subtasks.

    Milestones (with their subtasks) and tags are stored as JSON columns so the
    document-shaped structure used by the React app is preserved 1:1.
    """

    CATEGORY_CHOICES = [
        ("Academic", "Academic"),
        ("Personal", "Personal"),
        ("Career", "Career"),
        ("Health", "Health"),
        ("Projects", "Projects"),
    ]
    PRIORITY_CHOICES = [("High", "High"), ("Medium", "Medium"), ("Low", "Low")]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="goals"
    )
    # Identifier generated by the React client (e.g. "g-1730000000000").
    client_id = models.CharField(
        max_length=128, validators=[client_id_validator]
    )
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    target_date = models.CharField(max_length=50, blank=True, default="")
    progress = models.FloatField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    description = models.TextField(max_length=1000, blank=True, default="")
    milestones = models.JSONField(default=list, blank=True)
    tags = models.JSONField(default=list, blank=True)
    ai_tip = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["user", "client_id"], name="goals_goal_user_client_id_unique"
            ),
            models.CheckConstraint(
                condition=models.Q(progress__gte=0, progress__lte=100),
                name="goals_goal_progress_range",
            ),
        ]
        indexes = [models.Index(fields=["user", "-created_at"])]

    def __str__(self):
        return f"{self.title} ({self.user_id})"
